# Revenger v1.0 - By ComputerDude
# https://youtube.com/c/TheComputerDudeMC

# How much you get for completing a revenge
revenge-worth: 100

#How many revenges someone has had (UUID)
revenger-data:
  28f9bb08-b33c-4a7d-b098-ebf271383966: 0