name: Revenger
main: com.computerdude.revenger.Main
version: 1.0
authors: [ComputerDude, JustBru00]
depend: [Vault]
commands:
   revenger:
      aliases: [rv]
      description: Revenger plugin base command.
      usage: /<command>